import React, { useState, useEffect } from 'react';
import { Shield, Plus, Search, Edit, Trash2, Eye } from 'lucide-react';
import { userAPI } from '../services/api';
import { useAuth } from '../contexts/AuthContext';
import LoadingSpinner from '../components/common/LoadingSpinner';
import RoleModal from '../components/modals/RoleModal';
import toast from 'react-hot-toast';
import '../styles/common.css';
import './RoleManagement.css';

const RoleManagement = () => {
  const [roles, setRoles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedRole, setSelectedRole] = useState(null);
  const [showRoleModal, setShowRoleModal] = useState(false);
  const [modalMode, setModalMode] = useState('view'); // 'view', 'edit', 'create'

  useEffect(() => {
    loadRoles();
  }, []);

  const loadRoles = async () => {
    try {
      setLoading(true);
      console.log('Loading roles from API...');
      const response = await userAPI.getRoles();
      console.log('Roles API response:', response.data);
      
      const rolesData = response.data || [];
      console.log('Setting roles state with:', rolesData.length, 'roles');
      setRoles(rolesData);
      
      // Log each role for debugging
      rolesData.forEach(role => {
        console.log(`Role ${role.roleName}: ID = ${role.roleId}, Description = ${role.description || 'N/A'}`);
      });
      
    } catch (error) {
      console.error('Error loading roles:', error);
      toast.error('Không thể tải danh sách vai trò');
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
  };

  const filteredRoles = roles.filter(role => {
    const matchesSearch = 
      (role.roleName?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
      (role.description?.toLowerCase() || '').includes(searchTerm.toLowerCase());
    
    return matchesSearch;
  });

  const handleViewRole = (role) => {
    setSelectedRole(role);
    setModalMode('view');
    setShowRoleModal(true);
  };

  const handleEditRole = (role) => {
    setSelectedRole(role);
    setModalMode('edit');
    setShowRoleModal(true);
  };

  const handleCreateRole = () => {
    setSelectedRole(null);
    setModalMode('create');
    setShowRoleModal(true);
  };

  const handleSaveRole = async (roleId, roleData) => {
    try {
      console.log('=== SAVING ROLE DEBUG ===');
      console.log('Role ID:', roleId);
      console.log('Role ID type:', typeof roleId);
      console.log('Role Data:', roleData);
      console.log('Modal Mode:', modalMode);
      console.log('========================');
      
      // Validate input data
      if (!roleData.roleName || roleData.roleName.trim() === '') {
        toast.error('Tên vai trò không được để trống');
        return;
      }
      
      if (!roleData.description || roleData.description.trim() === '') {
        toast.error('Mô tả không được để trống');
        return;
      }
      
      // Ensure roleId is a number for API call
      const numericRoleId = typeof roleId === 'string' ? parseInt(roleId, 10) : roleId;
      console.log('Numeric Role ID:', numericRoleId);
      
      // Prepare data for API - DO NOT send permissions field at all
      // Backend will handle permissions internally based on roleName
      const apiData = {
        roleName: roleData.roleName.trim(),
        description: roleData.description.trim()
        // Do not include permissions field - backend will auto-generate
      };
      
      console.log('API data (permissions auto-generated by backend):', apiData);
      
      console.log('Data type check:', {
        roleName: typeof apiData.roleName,
        description: typeof apiData.description
      });
      
      // Verify no permissions field is being sent
      console.log('Fields being sent:', Object.keys(apiData));
      console.log('Has permissions field:', 'permissions' in apiData);
      
      // Validate data before sending
      if (apiData.roleName.length < 2) {
        toast.error('Tên vai trò phải có ít nhất 2 ký tự');
        return;
      }
      
      if (apiData.description.length < 5) {
        toast.error('Mô tả phải có ít nhất 5 ký tự');
        return;
      }
      
      if (modalMode === 'create') {
        console.log('Creating new role...');
        console.log('POST /api/users/roles with data:', JSON.stringify(apiData, null, 2));
        const response = await userAPI.createRole(apiData);
        console.log('Create response:', response);
        toast.success('Tạo vai trò thành công');
      } else {
        console.log('Updating existing role...');
        console.log(`PUT /api/users/roles/${roleId} with data:`, JSON.stringify(apiData, null, 2));
        console.log('Request body size:', JSON.stringify(apiData).length);
        console.log('Request body keys:', Object.keys(apiData));
        
        try {
          const response = await userAPI.updateRole(numericRoleId, apiData);
          console.log('Update response:', response);
          console.log('Response data:', response.data);
          console.log('Response status:', response.status);
          toast.success('Cập nhật vai trò thành công');
        } catch (updateError) {
          console.error('Update error details:', updateError);
          console.error('Update error response:', updateError.response);
          throw updateError; // Re-throw to be caught by outer catch
        }
      }
      
      // Close modal first
      setShowRoleModal(false);
      setSelectedRole(null);
      
      // Then reload roles data
      console.log('Reloading roles data...');
      await loadRoles();
      console.log('Roles data reloaded successfully');
      
      } catch (error) {
        console.error('Error saving role:', error);
        
        if (error.response) {
          console.error('=== ERROR RESPONSE DEBUG ===');
          console.error('Response status:', error.response.status);
          console.error('Response data:', error.response.data);
          console.error('Response headers:', error.response.headers);
          console.error('Request URL:', error.config?.url);
          console.error('Request method:', error.config?.method);
          console.error('Request data:', error.config?.data);
          console.error('============================');
          
          if (error.response.data && error.response.data.message) {
            toast.error(`Lỗi: ${error.response.data.message}`);
          } else if (error.response.status === 400) {
            // Show detailed 400 error
            const errorMsg = error.response.data?.error || error.response.data?.message || 'Dữ liệu không hợp lệ';
            toast.error(`Lỗi 400: ${errorMsg}`);
            console.error('400 Error details:', error.response.data);
            
            // Check for specific validation errors
            if (errorMsg.includes('roleName') || errorMsg.includes('tên vai trò')) {
              toast.error('Tên vai trò không hợp lệ hoặc đã tồn tại');
            } else if (errorMsg.includes('description') || errorMsg.includes('mô tả')) {
              toast.error('Mô tả không hợp lệ');
            }
          } else if (error.response.status === 401) {
            toast.error('Không có quyền thực hiện thao tác này');
          } else if (error.response.status === 404) {
            toast.error('Không tìm thấy vai trò');
          } else {
            toast.error('Không thể lưu vai trò');
          }
        } else {
          toast.error('Lỗi kết nối đến server');
        }
      
      throw error;
    }
  };

  const handleDeleteRole = async (role) => {
    if (window.confirm(`Bạn có chắc chắn muốn xóa vai trò "${role.roleName}"?`)) {
      try {
        console.log('Deleting role:', role.roleId);
        await userAPI.deleteRole(role.roleId);
        toast.success('Xóa vai trò thành công');
        loadRoles();
      } catch (error) {
        console.error('Error deleting role:', error);
        
        if (error.response) {
          console.error('Response status:', error.response.status);
          console.error('Response data:', error.response.data);
          
          if (error.response.data && error.response.data.message) {
            toast.error(`Lỗi: ${error.response.data.message}`);
          } else if (error.response.status === 400) {
            toast.error('Không thể xóa vai trò này. Có thể đang được sử dụng bởi người dùng.');
          } else if (error.response.status === 404) {
            toast.error('Không tìm thấy vai trò');
          } else if (error.response.status === 403) {
            toast.error('Không có quyền xóa vai trò này');
          } else {
            toast.error('Không thể xóa vai trò');
          }
        } else {
          toast.error('Lỗi kết nối đến server');
        }
      }
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('vi-VN');
  };

  const getRoleBadge = (roleName) => {
    const badgeMap = {
      'admin': { class: 'badge-admin', text: 'Admin' },
      'evm_staff': { class: 'badge-evms', text: 'EVM Staff' },
      'dealer_manager': { class: 'badge-dm', text: 'Dealer Manager' },
      'dealer_staff': { class: 'badge-ds', text: 'Dealer Staff' }
    };
    
    return badgeMap[roleName] || { class: 'badge-default', text: roleName };
  };

  if (loading) {
    return <LoadingSpinner text="Đang tải danh sách vai trò..." />;
  }

  return (
    <div className="role-management">
      <div className="page-header">
        <div className="page-title">
          <Shield size={32} />
          <h1>Quản lý vai trò</h1>
        </div>
        <p className="page-description">
          Quản lý các vai trò và quyền hạn trong hệ thống
        </p>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon">
            <Shield size={24} />
          </div>
          <div className="stat-content">
            <div className="stat-value">{roles.length}</div>
            <div className="stat-label">Tổng vai trò</div>
          </div>
        </div>
      </div>

      <div className="section-header">
        <h2>Danh sách vai trò</h2>
        <button className="btn btn-primary" onClick={handleCreateRole}>
          <Plus size={20} />
          Thêm vai trò
        </button>
      </div>


      <div className="search-bar">
        <Search className="search-icon" />
        <input 
          type="text" 
          placeholder="Tìm kiếm vai trò..." 
          value={searchTerm}
          onChange={handleSearch}
        />
      </div>

      <div className="table-container">
        <table className="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Tên vai trò</th>
              <th>Mô tả</th>
              <th>Quyền hạn</th>
              <th>Ngày tạo</th>
              <th>Thao tác</th>
            </tr>
          </thead>
          <tbody>
            {filteredRoles.length === 0 ? (
              <tr>
                <td colSpan="6" className="text-center">
                  <div className="empty-state">
                    <Shield size={48} />
                    <p>Không tìm thấy vai trò nào</p>
                  </div>
                </td>
              </tr>
            ) : (
              filteredRoles.map((role) => (
                <tr key={role.roleId}>
                  <td>{role.roleId}</td>
                  <td>
                    <div className="role-name-cell">
                      <span className={`badge ${getRoleBadge(role.roleName).class}`}>
                        {getRoleBadge(role.roleName).text}
                      </span>
                    </div>
                  </td>
                  <td>{role.description || 'N/A'}</td>
                  <td>
                    <div className="permissions-preview">
                      {role.permissions ? 'Có quyền hạn' : 'Không có quyền hạn'}
                    </div>
                  </td>
                  <td>{formatDate(role.createdAt)}</td>
                  <td>
                    <div className="action-buttons">
                      <button 
                        className="btn btn-sm btn-outline"
                        onClick={() => handleViewRole(role)}
                        title="Xem chi tiết"
                      >
                        <Eye size={16} />
                      </button>
                      <button 
                        className="btn btn-sm btn-outline"
                        onClick={() => handleEditRole(role)}
                        title="Chỉnh sửa"
                      >
                        <Edit size={16} />
                      </button>
                      <button 
                        className="btn btn-sm btn-danger"
                        onClick={() => handleDeleteRole(role)}
                        title="Xóa"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showRoleModal && (
        <RoleModal
          role={selectedRole}
          isOpen={showRoleModal}
          onClose={() => {
            setShowRoleModal(false);
            setSelectedRole(null);
          }}
          onSave={handleSaveRole}
          mode={modalMode}
        />
      )}
    </div>
  );
};

export default RoleManagement;
